/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ZuiNumberInput {
    /**
    * minimalNumber is the minimal value it takes the default value is set to 0 so it will not accept negative numbers
    */
    'minimalNumber': number;
    /**
    * placeholder text to set the placeholder attribute
    */
    'placeholder': string;
    /**
    * value prop that can set the value attribute
    */
    'value': string;
  }
  interface ZuiTextInput {
    /**
    * placeholder text to set the placeholder attribute
    */
    'placeholder': string;
  }
}

declare global {


  interface HTMLZuiNumberInputElement extends Components.ZuiNumberInput, HTMLStencilElement {}
  var HTMLZuiNumberInputElement: {
    prototype: HTMLZuiNumberInputElement;
    new (): HTMLZuiNumberInputElement;
  };

  interface HTMLZuiTextInputElement extends Components.ZuiTextInput, HTMLStencilElement {}
  var HTMLZuiTextInputElement: {
    prototype: HTMLZuiTextInputElement;
    new (): HTMLZuiTextInputElement;
  };
  interface HTMLElementTagNameMap {
    'zui-number-input': HTMLZuiNumberInputElement;
    'zui-text-input': HTMLZuiTextInputElement;
  }
}

declare namespace LocalJSX {
  interface ZuiNumberInput {
    /**
    * minimalNumber is the minimal value it takes the default value is set to 0 so it will not accept negative numbers
    */
    'minimalNumber'?: number;
    /**
    * placeholder text to set the placeholder attribute
    */
    'placeholder'?: string;
    /**
    * value prop that can set the value attribute
    */
    'value'?: string;
  }
  interface ZuiTextInput {
    /**
    * placeholder text to set the placeholder attribute
    */
    'placeholder'?: string;
  }

  interface IntrinsicElements {
    'zui-number-input': ZuiNumberInput;
    'zui-text-input': ZuiTextInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'zui-number-input': LocalJSX.ZuiNumberInput & JSXBase.HTMLAttributes<HTMLZuiNumberInputElement>;
      'zui-text-input': LocalJSX.ZuiTextInput & JSXBase.HTMLAttributes<HTMLZuiTextInputElement>;
    }
  }
}


