/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ZuiInput {
    /**
    * placeholder text
    */
    'placeholder': string;
  }
}

declare global {


  interface HTMLZuiInputElement extends Components.ZuiInput, HTMLStencilElement {}
  var HTMLZuiInputElement: {
    prototype: HTMLZuiInputElement;
    new (): HTMLZuiInputElement;
  };
  interface HTMLElementTagNameMap {
    'zui-input': HTMLZuiInputElement;
  }
}

declare namespace LocalJSX {
  interface ZuiInput {
    /**
    * placeholder text
    */
    'placeholder'?: string;
  }

  interface IntrinsicElements {
    'zui-input': ZuiInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'zui-input': LocalJSX.ZuiInput & JSXBase.HTMLAttributes<HTMLZuiInputElement>;
    }
  }
}


